# Generated by Django 4.0.6 on 2022-08-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=50)),
                ('gender', models.CharField(db_column='Gender', max_length=10)),
                ('phone', models.CharField(db_column='Phone', max_length=15)),
                ('date_of_birth', models.DateField(db_column='Date_of_birth')),
                ('password', models.CharField(db_column='Password', max_length=50)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
        ),
    ]
