# Generated by Django 4.0.6 on 2022-08-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('dept_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('treatment', models.TextField()),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Hospital',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_ID', models.CharField(db_column='d_ID', max_length=10)),
                ('p_ID', models.IntegerField(db_column='p_ID')),
                ('comment', models.CharField(db_column='comment', max_length=10000)),
                ('ratings', models.CharField(db_column='ratings', max_length=10)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('license_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('experience', models.CharField(default=None, max_length=20)),
                ('fees', models.IntegerField()),
                ('chamber', models.TextField()),
                ('designation', models.CharField(max_length=50)),
                ('ratings', models.CharField(default=None, max_length=10)),
                ('dept_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.department')),
                ('hos_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.hospital')),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
    ]
